PlataformaAvaliacao/PlataformaAvaliacao/Models/Disciplina.cs
namespace PlataformaAvaliacao.Models
{
    public class Disciplina
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
    }
}

PlataformaAvaliacao/PlataformaAvaliacao/Controllers/DisciplinaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlataformaAvaliacao.Data;
using PlataformaAvaliacao.Models;

namespace PlataformaAvaliacao.Controllers
{
    public class DisciplinaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DisciplinaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Disciplina
        public async Task<IActionResult> Index()
        {
            return View(await _context.Disciplinas.ToListAsync());
        }

        // GET: Disciplina/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disciplina = await _context.Disciplinas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disciplina == null)
            {
                return NotFound();
            }

            return View(disciplina);
        }

        // GET: Disciplina/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Disciplina/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Codigo")] Disciplina disciplina)
        {
            if (ModelState.IsValid)
            {
                _context.Add(disciplina);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(disciplina);
        }

        // GET: Disciplina/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disciplina = await _context.Disciplinas.FindAsync(id);
            if (disciplina == null)
            {
                return NotFound();
            }
            return View(disciplina);
        }

        // POST: Disciplina/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Codigo")] Disciplina disciplina)
        {
            if (id != disciplina.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(disciplina);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisciplinaExists(disciplina.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(disciplina);
        }

        // GET: Disciplina/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var disciplina = await _context.Disciplinas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (disciplina == null)
            {
                return NotFound();
            }

            return View(disciplina);
        }

        // POST: Disciplina/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var disciplina = await _context.Disciplinas.FindAsync(id);
            if (disciplina != null)
            {
                _context.Disciplinas.Remove(disciplina);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisciplinaExists(int id)
        {
            return _context.Disciplinas.Any(e => e.Id == id);
        }
    }
}

PlataformaAvaliacao/PlataformaAvaliacao/Views/Disciplina/Create.cshtml
@model PlataformaAvaliacao.Models.Disciplina
@{
    ViewData["Title"] = "Create";
}

<h1>Nova Disciplina</h1>

<hr />
<div class="card bg-metal border-light shadow-sm">
    <div class="card-body">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Nome" class="form-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Codigo" class="form-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary rounded-pill">Criar</button>
            <a asp-controller="Disciplina" asp-action="Index" class="btn btn-outline-light rounded-pill">Voltar</a>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PlataformaAvaliacao/PlataformaAvaliacao/Views/Disciplina/Delete.cshtml
@model PlataformaAvaliacao.Models.Disciplina
@{
    ViewData["Title"] = "Delete";
}

<h1>Excluír Disciplina</h1>

<hr />
<div class="card bg-metal border-secondary shadow-sm">
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Nome)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Nome)</dd>
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Codigo)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Codigo)</dd>
        </dl>
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-danger rounded-pill">Confirmar Exclusão</button>
            <a asp-action="Index" class="btn btn-outline-light rounded-pill">Cancelar</a>
        </form>
    </div>
</div>

PlataformaAvaliacao/PlataformaAvaliacao/Views/Disciplina/Details.cshtml
@model PlataformaAvaliacao.Models.Disciplina
@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes da Disciplina</h1>

<hr />
<div class="card bg-metal border-secondary shadow-sm">
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Nome)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Nome)</dd>
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Codigo)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Codigo)</dd>
        </dl>
        <a asp-controller="Disciplina" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary rounded-pill">Editar</a>
        <a asp-controller="Disciplina" asp-action="Index" class="btn btn-outline-light rounded-pill">Voltar</a>
    </div>
</div>

PlataformaAvaliacao/PlataformaAvaliacao/Views/Disciplina/Edit.cshtml
@model PlataformaAvaliacao.Models.Disciplina
@{
    ViewData["Title"] = "Edit";
}
<h1>Editar Disciplina</h1>
<hr />
<div class="card bg-metal border-light shadow-sm">
    <div class="card-body">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Nome" class="form-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Codigo" class="form-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary rounded-pill">Editar</button>
            <a asp-controller="Disciplina" asp-action="Index" class="btn btn-outline-light rounded-pill">Voltar</a>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PlataformaAvaliacao/PlataformaAvaliacao/Views/Disciplina/Index.cshtml
@model IEnumerable<PlataformaAvaliacao.Models.Disciplina>

@{
    ViewData["Title"] = "Index";
}
<h1 class="mb-4">Disciplina</h1>
<p>
    <a asp-action="Create" class="btn btn-success rounded-pill mb-3">+ Nova Avaliação</a>
</p>
<div class="table-responsive">
    <table class="table table-dark table-hover table-bordered rounded shadow-sm">
        <thead class="table-secondary text-dark">
            <tr>
                <th>@Html.DisplayNameFor(model => model.Nome)</th>
                <th>@Html.DisplayNameFor(model => model.Codigo)</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => item.Codigo)</td>
                    <td>
                        <a asp-controller="Disciplina" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary">Editar</a>
                        <a asp-controller="Disciplina" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-outline-info">Detalhes</a>
                        <a asp-controller="Disciplina" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>